services:
  db:
    image: postgres:15-alpine
    container_name: mverse_db
    networks:
      - mverse-network
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      POSTGRES_DB: ${DB_NAME:-mverse_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mverse_pgadmin
    networks:
      - mverse-network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@mverse.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: mverse_api
    networks:
      - mverse-network
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER:-admin}:${DB_PASSWORD:-password123}@db:5432/${DB_NAME:-mverse_db}
    volumes:
      - ./apps/backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./apps/frontend/m-verse
      dockerfile: Dockerfile
    container_name: mverse_web
    networks:
      - mverse-network
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    volumes:
      - ./apps/frontend/m-verse:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

networks:
  mverse-network:
    driver: bridge

volumes:
  postgres_data: